
language: node_js

node_js:
  - 8

os:
  - linux
dist: trusty

cache:
  directories:
    - ${HOME}/.esy

install:
  - npm install --global esy@0.6.10
  - esy install

addons:
  apt:
    sources:
    - avsm
    packages:
    - aspcud

script:
  - esy

